#!/bin/sh

luks_enabled() {
    [ "$bootparam_root" ]
}

LUKS_NAME=rootfs
LUKS_PASSWORD=refkit

luks_run() {
    C=0
    delay=${bootparam_rootdelay:-1}
    timeout=${bootparam_roottimeout:-5}

    if [ "`echo ${bootparam_root} | cut -c1-5`" = "UUID=" ]; then
        root_uuid=`echo $bootparam_root | cut -c6-`
        bootparam_root="/dev/disk/by-uuid/$root_uuid"
    fi

    if [ "`echo ${bootparam_root} | cut -c1-9`" = "PARTUUID=" ]; then
        root_uuid=`echo $bootparam_root | cut -c10-`
        bootparam_root="/dev/disk/by-partuuid/$root_uuid"
    fi

    while true; do
        if [ $(( $C * $delay )) -gt $timeout ]; then
            fatal "LUKS root partition '$bootparam_root' not found."
        fi

        if [ -e "$bootparam_root" ]; then
            cryptsetup isLuks "$bootparam_root" 2>/dev/null
            case $? in
              0) # LUKS volumne
                if echo "$LUKS_PASSWORD" | cryptsetup open --type luks "$bootparam_root" "$LUKS_NAME" --key-file -; then
                    bootparam_root="/dev/mapper/$LUKS_NAME"
                    return
                fi
                ;;
              1) # not a LUKS volume
                return
                ;;
              *) # something else
                debug "Error accessing "$bootparam_root" via cryptsetup"
                ;;
            esac
        fi

        debug "Sleeping for $delay second(s) to wait root to settle..."
        sleep $delay
        C=$(( $C + 1 ))
    done
}
