#!/bin/sh -ex

IMAGE_DIR=tmp-glibc/deploy/images/intel-corei7-64
SWTPM=$(ls tmp-glibc/work/*/swtpm-wrappers-native/1.0-r0/swtpm_oe.sh)
runqemu serial nographic my-installed-image wic intel-corei7-64 "qemuparams=-tpmdev emulator,id=tpm0,spawn=on,tpmstatedir=$IMAGE_DIR/my-tpm,logfile=$IMAGE_DIR/my-tpm/swtpm.log,path=$SWTPM -device tpm-tis,tpmdev=tpm0" ovmf
